[package]
name = "proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.65"
askama = "0.11.1"
heck = "0.4.0"
litrs = "0.2.3"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
