[package]
name = "basic"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1.20.1", features = ["sync", "rt", "macros"] }
anyhow = "1.0.62"
